package drai.dev.upgradedvanilla.modules.minecraft.stone.stone;

import drai.dev.upgradedvanilla.*;
import drai.dev.upgradedvanilla.helpers.*;
import drai.dev.upgradedvanilla.modules.minecraft.stone.*;
import drai.dev.upgradedvanilla.tag.*;
import net.minecraft.resources.*;
import net.minecraft.tags.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.*;

import java.io.*;
import java.util.*;

public class Calcite {
	public static String MATERIAL_NAME = "calcite";
	public static File calcitePalette;
	public static TagKey<Item> CALCITE_SLABS_ITEM_TAG;
	public static TagKey<Item> CALCITE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> SMOOTH_CALCITE_SLABS_ITEM_TAG;
	public static TagKey<Item> SMOOTH_CALCITE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> COBBLED_CALCITE_SLABS_ITEM_TAG;
	public static TagKey<Item> COBBLED_CALCITE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> MOSSY_COBBLED_CALCITE_SLABS_ITEM_TAG;
	public static TagKey<Item> MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> POLISHED_CALCITE_SLABS_ITEM_TAG;
	public static TagKey<Item> POLISHED_CALCITE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Item> POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static TagKey<Block> COBBLED_CALCITE_BLOCKS_BLOCK_TAG;
	public static TagKey<Item> CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Item> CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static TagKey<Block> CALCITE_BRICKS_BLOCK_TAG;
	public static TagKey<Item> CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static TagKey<Item> CRACKED_CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Item> MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static TagKey<Item> MOSSY_CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Item> CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> CRACKED_CALCITE_TILE_SLABS_ITEM_TAG;
	public static TagKey<Item> MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> MOSSY_CALCITE_TILE_SLABS_ITEM_TAG;
	public static TagKey<Item> CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static TagKey<Item> CRACKED_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Item> MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static TagKey<Item> MOSSY_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Block> MOSSY_COBBLED_CALCITE_BLOCKS_BLOCK_TAG;
	public static TagKey<Item> CALCITE_TILE_SLABS_ITEM_TAG;
	public static TagKey<Item> CALCITE_TILE_BLOCKS_ITEM_TAG;
	public static TagKey<Item> CHISELED_CALCITE_BRICK_SLABS_ITEM_TAG;
	public static TagKey<Item> CHISELED_CALCITE_BRICK_BLOCKS_ITEM_TAG;
	public static Block COBBLED_CALCITE;
	public static Block MOSSY_COBBLED_CALCITE;
	public static Block CALCITE_FURNACE;
	public static Block CALCITE_BLAST_FURNACE;
	public static Block CALCITE_DISPENSER;
	public static Block CALCITE_DROPPER;
	public static Block CALCITE_OBSERVER;
	public static Block CRACKED_POLISHED_CALCITE_BRICKS;
	public static Block MOSSY_POLISHED_CALCITE_BRICKS;
	public static Block CRACKED_CALCITE_TILES;
	public static Block MOSSY_CALCITE_TILES;
	public static Block CRACKED_CALCITE_BRICKS;
	public static Block MOSSY_CALCITE_BRICKS;
	public static Block SMOOTH_CALCITE;
	public static Block POLISHED_CALCITE;
	public static Block POLISHED_CALCITE_BRICKS;
	public static Block CALCITE_COAL_ORE;
	public static Block CALCITE_STAIRS;
	public static Block CALCITE_SLAB;
	public static Block CALCITE_WALL;
	public static Block CALCITE_TRAPDOOR;
	public static Block CALCITE_FENCE;
	public static Block CALCITE_BUTTON;
	public static Block CALCITE_FENCE_GATE;
	public static Block CALCITE_PRESSURE_PLATE;
	public static Block SMOOTH_CALCITE_STAIRS;
	public static Block SMOOTH_CALCITE_SLAB;
	public static Block SMOOTH_CALCITE_WALL;
	public static Block SMOOTH_CALCITE_TRAPDOOR;
	public static Block SMOOTH_CALCITE_FENCE;
	public static Block SMOOTH_CALCITE_BUTTON;
	public static Block SMOOTH_CALCITE_FENCE_GATE;
	public static Block SMOOTH_CALCITE_PRESSURE_PLATE;
	public static Block CALCITE_BRICKS;
	public static Block CALCITE_BRICK_BUTTON;
	public static Block CALCITE_BRICK_STAIRS;
	public static Block CALCITE_BRICK_SLAB;
	public static Block CALCITE_BRICK_WALL;
	public static Block CALCITE_BRICK_TRAPDOOR;
	public static Block CALCITE_BRICK_PRESSURE_PLATE;
	public static Block CALCITE_BRICK_FENCE;
	public static Block CALCITE_BRICK_FENCE_GATE;
	public static Block MOSSY_CALCITE_BRICK_STAIRS;
	public static Block MOSSY_CALCITE_BRICK_BUTTON;
	public static Block MOSSY_CALCITE_BRICK_SLAB;
	public static Block MOSSY_CALCITE_BRICK_WALL;
	public static Block MOSSY_CALCITE_BRICK_TRAPDOOR;
	public static Block MOSSY_CALCITE_BRICK_PRESSURE_PLATE;
	public static Block MOSSY_CALCITE_BRICK_FENCE;
	public static Block MOSSY_CALCITE_BRICK_FENCE_GATE;
	public static Block CRACKED_CALCITE_BRICK_STAIRS;
	public static Block CRACKED_CALCITE_BRICK_BUTTON;
	public static Block CRACKED_CALCITE_BRICK_SLAB;
	public static Block CRACKED_CALCITE_BRICK_WALL;
	public static Block CRACKED_CALCITE_BRICK_TRAPDOOR;
	public static Block CRACKED_CALCITE_BRICK_PRESSURE_PLATE;
	public static Block CRACKED_CALCITE_BRICK_FENCE;
	public static Block CRACKED_CALCITE_BRICK_FENCE_GATE;
	public static Block COBBLED_CALCITE_STAIRS;
	public static Block COBBLED_CALCITE_SLAB;
	public static Block COBBLED_CALCITE_WALL;
	public static Block COBBLED_CALCITE_TRAPDOOR;
	public static Block COBBLED_CALCITE_FENCE;
	public static Block COBBLED_CALCITE_BUTTON;
	public static Block COBBLED_CALCITE_FENCE_GATE;
	public static Block COBBLED_CALCITE_PRESSURE_PLATE;
	public static Block MOSSY_COBBLED_CALCITE_STAIRS;
	public static Block MOSSY_COBBLED_CALCITE_SLAB;
	public static Block MOSSY_COBBLED_CALCITE_WALL;
	public static Block MOSSY_COBBLED_CALCITE_TRAPDOOR;
	public static Block MOSSY_COBBLED_CALCITE_FENCE;
	public static Block MOSSY_COBBLED_CALCITE_BUTTON;
	public static Block MOSSY_COBBLED_CALCITE_FENCE_GATE;
	public static Block MOSSY_COBBLED_CALCITE_PRESSURE_PLATE;
	public static Block POLISHED_CALCITE_STAIRS;
	public static Block POLISHED_CALCITE_SLAB;
	public static Block POLISHED_CALCITE_WALL;
	public static Block POLISHED_CALCITE_TRAPDOOR;
	public static Block POLISHED_CALCITE_FENCE;
	public static Block POLISHED_CALCITE_BUTTON;
	public static Block POLISHED_CALCITE_FENCE_GATE;
	public static Block POLISHED_CALCITE_PRESSURE_PLATE;
	public static Block POLISHED_CALCITE_BRICK_STAIRS;
	public static Block POLISHED_CALCITE_BRICK_BUTTON;
	public static Block POLISHED_CALCITE_BRICK_SLAB;
	public static Block POLISHED_CALCITE_BRICK_WALL;
	public static Block POLISHED_CALCITE_BRICK_TRAPDOOR;
	public static Block POLISHED_CALCITE_BRICK_PRESSURE_PLATE;
	public static Block POLISHED_CALCITE_BRICK_FENCE;
	public static Block POLISHED_CALCITE_BRICK_FENCE_GATE;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_STAIRS;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_BUTTON;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_SLAB;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_WALL;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_TRAPDOOR;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_PRESSURE_PLATE;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_FENCE;
	public static Block MOSSY_POLISHED_CALCITE_BRICK_FENCE_GATE;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_STAIRS;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_BUTTON;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_SLAB;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_WALL;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_TRAPDOOR;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_PRESSURE_PLATE;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_FENCE;
	public static Block CRACKED_POLISHED_CALCITE_BRICK_FENCE_GATE;
	public static Block CALCITE_TILES;
	public static Block CALCITE_TILE_BUTTON;
	public static Block CALCITE_TILE_STAIRS;
	public static Block CALCITE_TILE_SLAB;
	public static Block CALCITE_TILE_WALL;
	public static Block CALCITE_TILE_TRAPDOOR;
	public static Block CALCITE_TILE_PRESSURE_PLATE;
	public static Block CALCITE_TILE_FENCE;
	public static Block CALCITE_TILE_FENCE_GATE;
	public static Block MOSSY_CALCITE_TILE_STAIRS;
	public static Block MOSSY_CALCITE_TILE_BUTTON;
	public static Block MOSSY_CALCITE_TILE_SLAB;
	public static Block MOSSY_CALCITE_TILE_WALL;
	public static Block MOSSY_CALCITE_TILE_TRAPDOOR;
	public static Block MOSSY_CALCITE_TILE_PRESSURE_PLATE;
	public static Block MOSSY_CALCITE_TILE_FENCE;
	public static Block MOSSY_CALCITE_TILE_FENCE_GATE;
	public static Block CRACKED_CALCITE_TILE_STAIRS;
	public static Block CRACKED_CALCITE_TILE_BUTTON;
	public static Block CRACKED_CALCITE_TILE_SLAB;
	public static Block CRACKED_CALCITE_TILE_WALL;
	public static Block CRACKED_CALCITE_TILE_TRAPDOOR;
	public static Block CRACKED_CALCITE_TILE_PRESSURE_PLATE;
	public static Block CRACKED_CALCITE_TILE_FENCE;
	public static Block CRACKED_CALCITE_TILE_FENCE_GATE;
	public static Block CHISELED_CALCITE_BRICKS;
	public static Block CHISELED_CALCITE_BRICKS_STAIRS;
	public static Block CHISELED_CALCITE_BRICKS_SLAB;
	public static Block CHISELED_CALCITE_BRICKS_WALL;
	public static Block CHISELED_CALCITE_BRICKS_TRAPDOOR;

	private static void registerTags(){
		CALCITE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"calcite_slabs"));
		CALCITE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKeyWithItems(new ResourceLocation(UpgradedVanilla.ID,"calcite_blocks"), List.of(new ResourceLocation("minecraft", "calcite")));
		SMOOTH_CALCITE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"smooth_calcite_slabs"));
		SMOOTH_CALCITE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"smooth_calcite_blocks"));
		CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"calcite_brick_slabs"));
		CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"calcite_brick_blocks"));
		POLISHED_CALCITE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"polished_calcite_slabs"));
		POLISHED_CALCITE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"polished_calcite_blocks"));
		POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"polished_calcite_brick_slabs"));
		POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"polished_calcite_brick_blocks"));
		CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cracked_polished_calcite_bricks"));
		CRACKED_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cracked_polished_calcite_brick_slabs"));
		MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_polished_calcite_bricks"));
		MOSSY_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_polished_calcite_brick_slabs"));
		COBBLED_CALCITE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cobbled_calcite_slabs"));
		COBBLED_CALCITE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cobbled_calcite_blocks"));
		MOSSY_COBBLED_CALCITE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_cobbled_calcite_slabs"));
		MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_cobbled_calcite_blocks"));
		COBBLED_CALCITE_BLOCKS_BLOCK_TAG = TagKeyHelper.createBlockTagKey(new ResourceLocation(UpgradedVanilla.ID,"cobbled_calcite_blocks"));
		CALCITE_BRICKS_BLOCK_TAG = TagKeyHelper.createBlockTagKey(new ResourceLocation(UpgradedVanilla.ID,"calcite_bricks"));
		CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cracked_calcite_bricks"));
		CRACKED_CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cracked_calcite_brick_slabs"));
		MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_calcite_bricks"));
		MOSSY_CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_calcite_brick_slabs"));
		MOSSY_COBBLED_CALCITE_BLOCKS_BLOCK_TAG = TagKeyHelper.createBlockTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_cobbled_calcite_blocks"));
		CALCITE_TILE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"calcite_tile_slabs"));
		CALCITE_TILE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"calcite_tile_blocks"));
		CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cracked_calcite_tiles"));
		CRACKED_CALCITE_TILE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"cracked_calcite_tile_slabs"));
		MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_calcite_tiles"));
		MOSSY_CALCITE_TILE_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"mossy_calcite_tile_slabs"));
		CHISELED_CALCITE_BRICK_SLABS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"chiseled_calcite_brick_slabs"));
		CHISELED_CALCITE_BRICK_BLOCKS_ITEM_TAG = TagKeyHelper.createItemTagKey(new ResourceLocation(UpgradedVanilla.ID,"chiseled_calcite_brick_blocks"));
	}
	public  static void register(){
		registerTags();
		calcitePalette = new File("C:\\Users\\Stijn\\Desktop\\Upgraded Vanilla project\\template data\\Stone\\Palletes\\calcitePalette.png");
		registerMinecraftBlocks();
	}

	public static void registerMinecraftBlocks(){
		CALCITE_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		CALCITE_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CALCITE_SLABS_ITEM_TAG));
		CALCITE_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_SLABS_ITEM_TAG, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_SLABS_ITEM_TAG, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		COBBLED_CALCITE = MinecraftStoneBlocks.cobbledStoneBlock(MATERIAL_NAME, Blocks.CALCITE,
				List.of(COBBLED_CALCITE_BLOCKS_BLOCK_TAG, BlockTags.MINEABLE_WITH_PICKAXE), List.of(COBBLED_CALCITE_BLOCKS_ITEM_TAG, UVCommonItemTags.COBBLESTONES));
		COBBLED_CALCITE_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		COBBLED_CALCITE_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		COBBLED_CALCITE_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(COBBLED_CALCITE_SLABS_ITEM_TAG));
		COBBLED_CALCITE_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		COBBLED_CALCITE_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		COBBLED_CALCITE_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_SLABS_ITEM_TAG, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		COBBLED_CALCITE_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_SLABS_ITEM_TAG, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		COBBLED_CALCITE_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, COBBLED_CALCITE, COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE = MinecraftStoneBlocks.mossyCobbledStoneBlock(MATERIAL_NAME, COBBLED_CALCITE,
				List.of(MOSSY_COBBLED_CALCITE_BLOCKS_BLOCK_TAG, BlockTags.MINEABLE_WITH_PICKAXE), List.of(UVCommonItemTags.COBBLESTONES));
		MOSSY_COBBLED_CALCITE_BUTTON = MinecraftStoneBlocks.mossyCobbledStoneButtonBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_BUTTON, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE_STAIRS = MinecraftStoneBlocks.mossyCobbledStoneStairsBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_STAIRS, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE_SLAB = MinecraftStoneBlocks.mossyCobbledStoneSlabBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_SLAB, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(MOSSY_COBBLED_CALCITE_SLABS_ITEM_TAG));
		MOSSY_COBBLED_CALCITE_WALL = MinecraftStoneBlocks.mossyCobbledStoneWallBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_WALL, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE_TRAPDOOR = MinecraftStoneBlocks.mossyCobbledStoneTrapdoorBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_TRAPDOOR, MOSSY_COBBLED_CALCITE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE_FENCE = MinecraftStoneBlocks.mossyCobbledStoneFenceBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_FENCE, MOSSY_COBBLED_CALCITE_SLABS_ITEM_TAG, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE_FENCE_GATE = MinecraftStoneBlocks.mossyCobbledStoneFenceGateBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_FENCE_GATE,MOSSY_COBBLED_CALCITE_SLABS_ITEM_TAG, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_COBBLED_CALCITE_PRESSURE_PLATE = MinecraftStoneBlocks.mossyCobbledStonePressurePlateBlock(MATERIAL_NAME, MOSSY_COBBLED_CALCITE, COBBLED_CALCITE_PRESSURE_PLATE, MOSSY_COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_BRICKS = MinecraftStoneBlocks.stoneBricksBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(CALCITE_BRICKS_BLOCK_TAG, BlockTags.MINEABLE_WITH_PICKAXE), List.of(CALCITE_BRICK_BLOCKS_ITEM_TAG));
		CALCITE_BRICK_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(),List.of());
		CALCITE_BRICK_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_BRICK_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_SLABS_ITEM_TAG, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_BRICK_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_SLABS_ITEM_TAG, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_BRICK_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CALCITE_BRICK_SLABS_ITEM_TAG));
		CALCITE_BRICK_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_BRICK_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_BRICK_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_BRICKS = MinecraftStoneBlocks.crackedStoneBricksBlock(MATERIAL_NAME, CALCITE_BRICKS,
				List.of(CALCITE_BRICKS_BLOCK_TAG, BlockTags.MINEABLE_WITH_PICKAXE), List.of(CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG));
		CRACKED_CALCITE_BRICK_STAIRS = MinecraftStoneBlocks.crackedStoneBrickStairsBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_STAIRS,CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_BRICK_BUTTON = MinecraftStoneBlocks.crackedStoneBrickButtonBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_BUTTON,CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(),List.of());
		CRACKED_CALCITE_BRICK_SLAB = MinecraftStoneBlocks.crackedStoneBrickSlabBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_SLAB, CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CRACKED_CALCITE_BRICK_SLABS_ITEM_TAG));
		CRACKED_CALCITE_BRICK_WALL = MinecraftStoneBlocks.crackedStoneBrickWallBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_WALL,CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_BRICK_TRAPDOOR = MinecraftStoneBlocks.crackedStoneBrickTrapdoorBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_TRAPDOOR, CRACKED_CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_BRICK_PRESSURE_PLATE = MinecraftStoneBlocks.crackedStoneBrickPressurePlateBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_PRESSURE_PLATE, CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_BRICK_FENCE = MinecraftStoneBlocks.crackedStoneBrickFenceBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_FENCE,CRACKED_CALCITE_BRICK_SLABS_ITEM_TAG, CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_BRICK_FENCE_GATE = MinecraftStoneBlocks.crackedStoneBrickFenceGateBlock(MATERIAL_NAME, CRACKED_CALCITE_BRICKS, CALCITE_BRICK_FENCE_GATE,CRACKED_CALCITE_BRICK_SLABS_ITEM_TAG, CRACKED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_BRICKS = MinecraftStoneBlocks.mossyStoneBricksBlock(MATERIAL_NAME, CALCITE_BRICKS, CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(CALCITE_BRICKS_BLOCK_TAG, BlockTags.MINEABLE_WITH_PICKAXE), List.of(MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG));
		MOSSY_CALCITE_BRICK_STAIRS = MinecraftStoneBlocks.mossyStoneBrickStairsBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_STAIRS,MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_BRICK_BUTTON = MinecraftStoneBlocks.mossyStoneBrickButtonBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_BUTTON,MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		MOSSY_CALCITE_BRICK_SLAB = MinecraftStoneBlocks.mossyStoneBrickSlabBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_SLAB, MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(MOSSY_CALCITE_BRICK_SLABS_ITEM_TAG));
		MOSSY_CALCITE_BRICK_WALL = MinecraftStoneBlocks.mossyStoneBrickWallBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_WALL,MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_BRICK_TRAPDOOR = MinecraftStoneBlocks.mossyStoneBrickTrapdoorBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_TRAPDOOR, MOSSY_CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_BRICK_PRESSURE_PLATE = MinecraftStoneBlocks.mossyStoneBrickPressurePlateBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_PRESSURE_PLATE, MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_BRICK_FENCE = MinecraftStoneBlocks.mossyStoneBrickFenceBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_FENCE, MOSSY_CALCITE_BRICK_SLABS_ITEM_TAG, MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_BRICK_FENCE_GATE = MinecraftStoneBlocks.mossyStoneBrickFenceGateBlock(MATERIAL_NAME, MOSSY_CALCITE_BRICKS, CALCITE_BRICK_FENCE_GATE, MOSSY_CALCITE_BRICK_SLABS_ITEM_TAG, MOSSY_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		SMOOTH_CALCITE = MinecraftStoneBlocks.smoothStoneBlock(MATERIAL_NAME, Blocks.CALCITE,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(SMOOTH_CALCITE_BLOCKS_ITEM_TAG), calcitePalette);
		SMOOTH_CALCITE_SLAB = MinecraftStoneBlocks.smoothStoneSlabBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(UVCommonItemTags.COBBLESTONES), calcitePalette);
		SMOOTH_CALCITE_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		SMOOTH_CALCITE_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		SMOOTH_CALCITE_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		SMOOTH_CALCITE_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		SMOOTH_CALCITE_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_SLABS_ITEM_TAG, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		SMOOTH_CALCITE_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_SLABS_ITEM_TAG, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		SMOOTH_CALCITE_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, SMOOTH_CALCITE, SMOOTH_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE = MinecraftStoneBlocks.polishedStoneBlock(MATERIAL_NAME, Blocks.CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(POLISHED_CALCITE_BLOCKS_ITEM_TAG));
		POLISHED_CALCITE_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(POLISHED_CALCITE_SLABS_ITEM_TAG));
		POLISHED_CALCITE_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_SLABS_ITEM_TAG, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_SLABS_ITEM_TAG, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, POLISHED_CALCITE, POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		POLISHED_CALCITE_BRICKS = MinecraftStoneBlocks.polishedStoneBricksBlock(MATERIAL_NAME, Blocks.CALCITE,POLISHED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(CALCITE_BRICKS_BLOCK_TAG, BlockTags.MINEABLE_WITH_PICKAXE), List.of(POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG));
		POLISHED_CALCITE_BRICK_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_BRICK_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		POLISHED_CALCITE_BRICK_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG));
		POLISHED_CALCITE_BRICK_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_BRICK_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_BRICK_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_BRICK_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		POLISHED_CALCITE_BRICK_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_POLISHED_CALCITE_BRICKS = MinecraftStoneBlocks.crackedPolishedStoneBricksBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG));
		CRACKED_POLISHED_CALCITE_BRICK_STAIRS = MinecraftStoneBlocks.crackedStoneBrickStairsBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_STAIRS,CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_POLISHED_CALCITE_BRICK_BUTTON = MinecraftStoneBlocks.crackedStoneBrickButtonBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BUTTON,CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(),List.of());
		CRACKED_POLISHED_CALCITE_BRICK_SLAB = MinecraftStoneBlocks.crackedStoneBrickSlabBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_SLAB, CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CRACKED_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG));
		CRACKED_POLISHED_CALCITE_BRICK_WALL = MinecraftStoneBlocks.crackedStoneBrickWallBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_WALL,CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_POLISHED_CALCITE_BRICK_TRAPDOOR = MinecraftStoneBlocks.crackedStoneBrickTrapdoorBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_TRAPDOOR, CRACKED_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_POLISHED_CALCITE_BRICK_PRESSURE_PLATE = MinecraftStoneBlocks.crackedStoneBrickPressurePlateBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_PRESSURE_PLATE, CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_POLISHED_CALCITE_BRICK_FENCE = MinecraftStoneBlocks.crackedStoneBrickFenceBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_FENCE,CRACKED_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG, CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_POLISHED_CALCITE_BRICK_FENCE_GATE = MinecraftStoneBlocks.crackedStoneBrickFenceGateBlock(MATERIAL_NAME, CRACKED_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_FENCE_GATE,CRACKED_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG, CRACKED_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_POLISHED_CALCITE_BRICKS = MinecraftStoneBlocks.mossyPolishedStoneBricksBlock(MATERIAL_NAME, POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG));
		MOSSY_POLISHED_CALCITE_BRICK_STAIRS = MinecraftStoneBlocks.mossyStoneBrickStairsBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_STAIRS,MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_POLISHED_CALCITE_BRICK_BUTTON = MinecraftStoneBlocks.mossyStoneBrickButtonBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_BUTTON,MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		MOSSY_POLISHED_CALCITE_BRICK_SLAB = MinecraftStoneBlocks.mossyStoneBrickSlabBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_SLAB, MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(MOSSY_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG));
		MOSSY_POLISHED_CALCITE_BRICK_WALL = MinecraftStoneBlocks.mossyStoneBrickWallBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_WALL,MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_POLISHED_CALCITE_BRICK_TRAPDOOR = MinecraftStoneBlocks.mossyStoneBrickTrapdoorBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_TRAPDOOR, MOSSY_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_POLISHED_CALCITE_BRICK_PRESSURE_PLATE = MinecraftStoneBlocks.mossyStoneBrickPressurePlateBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_PRESSURE_PLATE, MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_POLISHED_CALCITE_BRICK_FENCE = MinecraftStoneBlocks.mossyStoneBrickFenceBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_FENCE, MOSSY_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG, MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_POLISHED_CALCITE_BRICK_FENCE_GATE = MinecraftStoneBlocks.mossyStoneBrickFenceGateBlock(MATERIAL_NAME, MOSSY_POLISHED_CALCITE_BRICKS, POLISHED_CALCITE_BRICK_FENCE_GATE, MOSSY_POLISHED_CALCITE_BRICK_SLABS_ITEM_TAG, MOSSY_POLISHED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TILES = MinecraftStoneBlocks.stoneTilesBlock(MATERIAL_NAME, CALCITE_BRICKS, COBBLED_CALCITE, POLISHED_CALCITE, CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CALCITE_TILE_BLOCKS_ITEM_TAG));
		CALCITE_TILE_BUTTON = MinecraftStoneBlocks.stoneButtonBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(),List.of());
		CALCITE_TILE_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TILE_FENCE = MinecraftStoneBlocks.stoneFenceBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_SLABS_ITEM_TAG, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TILE_FENCE_GATE = MinecraftStoneBlocks.stoneFenceGateBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_SLABS_ITEM_TAG, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TILE_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CALCITE_TILE_SLABS_ITEM_TAG));
		CALCITE_TILE_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TILE_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_TILE_PRESSURE_PLATE = MinecraftStoneBlocks.stonePressurePlateBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_TILES = MinecraftStoneBlocks.crackedStoneTilesBlock(MATERIAL_NAME, CALCITE_TILES,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG));
		CRACKED_CALCITE_TILE_STAIRS = MinecraftStoneBlocks.crackedStoneTileStairsBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_STAIRS,CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_TILE_BUTTON = MinecraftStoneBlocks.crackedStoneTileButtonBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_BUTTON,CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(),List.of());
		CRACKED_CALCITE_TILE_SLAB = MinecraftStoneBlocks.crackedStoneTileSlabBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_SLAB, CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CRACKED_CALCITE_TILE_SLABS_ITEM_TAG));
		CRACKED_CALCITE_TILE_WALL = MinecraftStoneBlocks.crackedStoneTileWallBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_WALL,CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_TILE_TRAPDOOR = MinecraftStoneBlocks.crackedStoneTileTrapdoorBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_TRAPDOOR, CRACKED_CALCITE_TILE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_TILE_PRESSURE_PLATE = MinecraftStoneBlocks.crackedStoneTilePressurePlateBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_PRESSURE_PLATE, CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_TILE_FENCE = MinecraftStoneBlocks.crackedStoneTileFenceBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_FENCE,CRACKED_CALCITE_TILE_SLABS_ITEM_TAG, CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CRACKED_CALCITE_TILE_FENCE_GATE = MinecraftStoneBlocks.crackedStoneTileFenceGateBlock(MATERIAL_NAME, CRACKED_CALCITE_TILES, CALCITE_TILE_FENCE_GATE,CRACKED_CALCITE_TILE_SLABS_ITEM_TAG, CRACKED_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_TILES = MinecraftStoneBlocks.mossyStoneTilesBlock(MATERIAL_NAME, CALCITE_TILES, CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG));
		MOSSY_CALCITE_TILE_STAIRS = MinecraftStoneBlocks.mossyStoneTileStairsBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_STAIRS,MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_TILE_BUTTON = MinecraftStoneBlocks.mossyStoneTileButtonBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_BUTTON,MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(), List.of());
		MOSSY_CALCITE_TILE_SLAB = MinecraftStoneBlocks.mossyStoneTileSlabBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_SLAB, MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(MOSSY_CALCITE_TILE_SLABS_ITEM_TAG));
		MOSSY_CALCITE_TILE_WALL = MinecraftStoneBlocks.mossyStoneTileWallBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_WALL,MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_TILE_TRAPDOOR = MinecraftStoneBlocks.mossyStoneTileTrapdoorBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_TRAPDOOR, MOSSY_CALCITE_TILE_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_TILE_PRESSURE_PLATE = MinecraftStoneBlocks.mossyStoneTilePressurePlateBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_PRESSURE_PLATE, MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_TILE_FENCE = MinecraftStoneBlocks.mossyStoneTileFenceBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_FENCE, MOSSY_CALCITE_TILE_SLABS_ITEM_TAG, MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		MOSSY_CALCITE_TILE_FENCE_GATE = MinecraftStoneBlocks.mossyStoneTileFenceGateBlock(MATERIAL_NAME, MOSSY_CALCITE_TILES, CALCITE_TILE_FENCE_GATE, MOSSY_CALCITE_TILE_SLABS_ITEM_TAG, MOSSY_CALCITE_TILE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.FENCE_GATES,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CHISELED_CALCITE_BRICKS = MinecraftStoneBlocks.chiseledStoneBricksBlock(MATERIAL_NAME, CALCITE_BRICKS, Blocks.CALCITE, CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CALCITE_TILE_BLOCKS_ITEM_TAG));
		CHISELED_CALCITE_BRICKS_STAIRS = MinecraftStoneBlocks.stoneStairsBlock(MATERIAL_NAME, CHISELED_CALCITE_BRICKS, CHISELED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CHISELED_CALCITE_BRICKS_SLAB = MinecraftStoneBlocks.stoneSlabBlock(MATERIAL_NAME, CHISELED_CALCITE_BRICKS, CHISELED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE), List.of(CHISELED_CALCITE_BRICK_SLABS_ITEM_TAG));
		CHISELED_CALCITE_BRICKS_WALL = MinecraftStoneBlocks.stoneWallBlock(MATERIAL_NAME, CHISELED_CALCITE_BRICKS, CHISELED_CALCITE_BRICK_BLOCKS_ITEM_TAG,
				List.of(BlockTags.WALLS,BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CHISELED_CALCITE_BRICKS_TRAPDOOR = MinecraftStoneBlocks.stoneTrapdoorBlock(MATERIAL_NAME, CHISELED_CALCITE_BRICKS, CHISELED_CALCITE_BRICK_SLABS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of());
		CALCITE_FURNACE = MinecraftStoneBlocks.furnaceBlock(MATERIAL_NAME, COBBLED_CALCITE,COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(UVCommonItemTags.FURNACES), calcitePalette,SoundType.CALCITE);
		CALCITE_BLAST_FURNACE = MinecraftStoneBlocks.blastFurnaceBlock(MATERIAL_NAME, CALCITE_FURNACE, Blocks.CALCITE,COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(UVCommonItemTags.FURNACES), calcitePalette,SoundType.CALCITE);
		CALCITE_DISPENSER = MinecraftStoneBlocks.dispenserBlock(MATERIAL_NAME, CALCITE_FURNACE, Blocks.CALCITE,COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(UVCommonItemTags.FURNACES), calcitePalette,SoundType.CALCITE);
		CALCITE_DROPPER = MinecraftStoneBlocks.dropperBlock(MATERIAL_NAME, CALCITE_FURNACE, Blocks.CALCITE,COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(UVCommonItemTags.FURNACES), calcitePalette,SoundType.CALCITE);
		CALCITE_OBSERVER = MinecraftStoneBlocks.observerBlock(MATERIAL_NAME, Blocks.CALCITE,COBBLED_CALCITE_BLOCKS_ITEM_TAG,
				List.of(BlockTags.MINEABLE_WITH_PICKAXE),List.of(UVCommonItemTags.FURNACES), calcitePalette,SoundType.CALCITE);
		CALCITE_COAL_ORE = MinecraftStoneBlocks.oreSet(MATERIAL_NAME, COBBLED_CALCITE, CALCITE_BLOCKS_ITEM_TAG,SoundType.CALCITE);
	}
}
